# Google Cloud Build ì„¤ì • íŒŒì¼
# - Docker build -> Artifact Registry push -> Cloud Run deploy
# - ì•ˆì •ì„± ê°œì„ : repo ë³€ìˆ˜í™” / update-env-vars / update-secrets / allow-unauth ì˜µì…˜í™” / secret ë²„ì „ ê³ ì •

substitutions:
  _SERVICE_NAME: 'role'
  _REGION: 'us-east1'
  _AR_REPO: 'cloud-run-source-deploy'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _GCS_BUCKET_NAME: 'roleplay-bucket'
  _ALLOW_UNAUTH: 'true'
  _RUNTIME_SA: 'runtime-sa@${PROJECT_ID}.iam.gserviceaccount.com'
  _SIGNED_URL_TTL_MINUTES: '30'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "ðŸš€ Deploying to Cloud Run..."

        ALLOW_FLAG=""
        if [ "${_ALLOW_UNAUTH}" = "true" ]; then
          ALLOW_FLAG="--allow-unauthenticated"
        fi

        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA} \
          --region ${_REGION} \
          --platform managed \
          ${ALLOW_FLAG} \
          --service-account ${_RUNTIME_SA} \
          --memory ${_MEMORY} \
          --cpu ${_CPU} \
          --min-instances ${_MIN_INSTANCES} \
          --max-instances ${_MAX_INSTANCES} \
          --port 8080 \
          --timeout 300 \
          --update-env-vars NODE_ENV=production,AI_PROVIDER=gemini,GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},SIGNED_URL_TTL_MINUTES=${_SIGNED_URL_TTL_MINUTES} \
          --update-secrets JWT_SECRET=jwt-secret:1,DATABASE_URL=database-url:1,GOOGLE_API_KEY=google-api-key:1

        gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --format 'value(status.url)'


images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
