steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'
      - '.'

  # 2. Container Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'

  # 3. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'role'
      - '--image'
      - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--startup-cpu-boost'
      - '--cpu-throttling'
      # Startup probe: Cloud Run will not route traffic until /_ah/ready
      # returns HTTP 200.  This prevents 503 errors during cold start while
      # routes and the database connection are still initialising.
      # Budget: period(2s) × threshold(60) = 120s max startup time.
      # DB retry loop: 15 attempts with exponential backoff (1s→5s cap) ≈ 55s.
      - '--startup-probe-http-get-path=/_ah/ready'
      - '--startup-probe-period=2'
      - '--startup-probe-failure-threshold=60'
      - '--startup-probe-timeout=3'
      # Liveness probe: detect stuck/unresponsive containers and restart them
      # rather than continuing to serve 503 errors.
      - '--liveness-probe-http-get-path=/_ah/health'
      - '--liveness-probe-period=15'
      - '--liveness-probe-failure-threshold=3'
      - '--liveness-probe-timeout=5'
      # Cloud SQL 연결: Cloud SQL Auth Proxy 사이드카를 활성화하여
      # /cloudsql/INSTANCE_CONNECTION_NAME Unix 소켓을 통해 연결합니다.
      - '--add-cloudsql-instances=role-20260129:us-east1:dbrole'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      # Secret Manager에서 시크릿 주입
      # 사전에 Google Cloud Secret Manager에 아래 시크릿들을 생성해야 합니다:
      # - jwt-secret: JWT 인증용 시크릿 키
      # - database-url: PostgreSQL 연결 문자열
      # - google-api-key: Gemini API 키
      # (선택) elevenlabs-api-key: TTS 기능용 - 필요시 아래 줄에 추가
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
