steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-roleplay-training:$COMMIT_SHA'
      - '.'

  # 2. Container Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-roleplay-training:$COMMIT_SHA'

  # 3. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-roleplay-training'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-roleplay-training:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--startup-cpu-boost'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      # Secret Manager에서 시크릿 주입
      # 사전에 Google Cloud Secret Manager에 아래 시크릿들을 생성해야 합니다:
      # - jwt-secret: JWT 인증용 시크릿 키
      # - database-url: PostgreSQL 연결 문자열
      # - google-api-key: Gemini API 키
      # (선택) elevenlabs-api-key: TTS 기능용 - 필요시 아래 줄에 추가
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/ai-roleplay-training:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
