steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'
      - '.'

  # 2. Container Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'

  # 3. 기존 서비스에서 잘못된 시크릿 참조 제거 후 Cloud Run에 배포
  # 이전 배포에서 남아있는 JWT_SECRET, OPENAI_API_KEY 등 잘못된 시크릿 참조를
  # 명시적으로 제거한 뒤 올바른 시크릿으로 배포합니다.
  # 단일 bash 스크립트로 실행하여 중간 실패 시 에러가 노출되도록 합니다.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e

        echo "=== Step 1: Remove stale secret references ==="
        # Explicitly remove known stale Secret Manager references that use
        # uppercase names (JWT_SECRET, OPENAI_API_KEY) which don't exist.
        # --remove-secrets is more targeted than --clear-secrets and won't
        # fail when the secret env var is already absent.
        gcloud run services describe role \
          --region us-east1 \
          --platform managed \
          --format='yaml(spec.template.spec.containers[0].env)' 2>/dev/null \
          && echo "Current service found, checking for stale secrets..." \
          || { echo "No existing service found (first deploy), skipping cleanup."; }

        # Try to remove stale secrets; ignore errors if they don't exist
        gcloud run services update role \
          --region us-east1 \
          --platform managed \
          --remove-secrets=JWT_SECRET,OPENAI_API_KEY \
          --quiet 2>&1 || echo "Note: Could not remove stale secrets (may not exist). Continuing..."

        # Also clear any remaining unknown stale secret references
        gcloud run services update role \
          --region us-east1 \
          --platform managed \
          --clear-secrets \
          --quiet 2>&1 || echo "Note: Could not clear secrets (may be first deploy). Continuing..."

        echo "=== Step 2: Deploy to Cloud Run ==="
        gcloud run deploy role \
          --image gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --min-instances 1 \
          --max-instances 10 \
          --port 8080 \
          --startup-cpu-boost \
          --cpu-throttling \
          --startup-probe-http-get-path=/_ah/ready \
          --startup-probe-period=2 \
          --startup-probe-failure-threshold=60 \
          --startup-probe-timeout=3 \
          --liveness-probe-http-get-path=/_ah/health \
          --liveness-probe-period=15 \
          --liveness-probe-failure-threshold=3 \
          --liveness-probe-timeout=5 \
          --add-cloudsql-instances=role-20260129:us-east1:dbrole \
          --set-env-vars=NODE_ENV=production,AI_PROVIDER=gemini \
          --set-secrets=JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest,GEMINI_API_KEY=google-api-key:latest

images:
  - 'gcr.io/$PROJECT_ID/roleplaybot:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
