steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/roleplaybot/role:$COMMIT_SHA'
      - '.'

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/roleplaybot/role:$COMMIT_SHA'

  # 3. Deploy to Cloud Run
  # --set-secrets replaces ALL existing secret-backed env vars on the service,
  # which automatically removes stale references to non-existent secrets
  # (e.g., uppercase JWT_SECRET, OPENAI_API_KEY in Secret Manager).
  # No separate cleanup step is needed; previous approaches using
  # --remove-secrets / --clear-secrets failed because those intermediate
  # service updates also create revisions that can't start.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        gcloud run deploy role \
          --image us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/roleplaybot/role:$COMMIT_SHA \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --min-instances 1 \
          --max-instances 10 \
          --port 8080 \
          --startup-cpu-boost \
          --cpu-throttling \
          --startup-probe-http-get-path=/_ah/ready \
          --startup-probe-period=2 \
          --startup-probe-failure-threshold=60 \
          --startup-probe-timeout=3 \
          --liveness-probe-http-get-path=/_ah/health \
          --liveness-probe-period=15 \
          --liveness-probe-failure-threshold=3 \
          --liveness-probe-timeout=5 \
          --add-cloudsql-instances=role-20260129:us-east1:dbrole \
          --set-env-vars=NODE_ENV=production,AI_PROVIDER=gemini \
          --set-secrets=JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest,GEMINI_API_KEY=google-api-key:latest

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/roleplaybot/role:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
