import type { RealtimeSession } from '../../../server/services/voice/types';

export function makeSession(overrides: Partial<RealtimeSession> = {}): RealtimeSession {
  return {
    id: 'test-session',
    conversationId: 'conv-1',
    scenarioId: 'scenario-1',
    personaId: 'persona-1',
    personaName: 'TestPersona',
    userId: 'user-1',
    userName: '사용자',
    clientWs: {} as any,
    geminiSession: null,
    currentTranscript: '',
    userTranscriptBuffer: '',
    audioBuffer: [],
    startTime: Date.now(),
    lastActivityTime: Date.now(),
    totalUserTranscriptLength: 0,
    totalAiTranscriptLength: 0,
    realtimeModel: 'gemini-live',
    hasReceivedFirstAIResponse: false,
    hasTriggeredFirstGreeting: false,
    firstGreetingRetryCount: 0,
    isInterrupted: false,
    turnSeq: 0,
    cancelledTurnSeq: 0,
    sessionResumptionToken: null,
    isReconnecting: false,
    reconnectAttempts: 0,
    systemInstructions: 'instructions',
    voiceGender: 'female',
    recentMessages: [],
    selectedVoice: null,
    goAwayWarningTime: null,
    pendingClientReady: null,
    userLanguage: 'ko',
    pendingMessages: [],
    outgoingMessageIndex: 0,
    hasReceivedFirstAIAudio: false,
    hasReceivedFirstTranscriptDelta: false,
    greetingResponseCount: 0,
    userTurnsCompleted: 0,
    simulationState: null,
    scenarioRunId: null,
    toolCallCountThisTurn: 0,
    emotionCallCountThisTurn: 0,
    currentTurnIncidentFired: false,
    lastEvaluatedUserTurnIndex: -1,
    lastEvaluatedUserTurnId: null,
    lastFinalizedUserTranscriptHash: null,
    lastClientContentSentAt: 0,
    greetingTimeoutId: null,
    pendingIsResuming: false,
    usingReconnectInstructions: false,
    activePersonaIndex: 0,
    voiceId: null,
    ...overrides,
  };
}
